name = "msgraph-github-oauth"
main = "worker.js"
compatibility_date = "2024-01-01"

# After deploying, set secrets:
#   wrangler secret put GITHUB_CLIENT_ID
#   wrangler secret put GITHUB_CLIENT_SECRET
